apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:v1.1
        command: ["sleep", "infinity"]
        resources:
          limits:
            nvidia.com/gpu: 1
  backoffLimit: 4